---
platform: linux

resources:
- name: git-repo
  type: git
  source:
    branch: master
    username: chirag1603
    password: mukesh1234
    uri: https://github.com/chirag1603/concourse_test.git

jobs:
- name: executing-terraform
  plan:
  - get: git-repo
  - task: terraform-start
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hashicorp/terraform
          tag: latest
      inputs:
      - name: git-repo
      run:
        path: /bin/sh
        args:
        - -c
        - |
          echo "Hello World"
          terraform init
          pwd
          ls -lrta
          cd git-repo
          pwd          
          ls -lrta
