---
platform: linux

resources:
- name: git-repo
  type: git
  source:
    branch: master
    username: chirag1603
    password: mukesh1234
    uri: https://github.com/chirag1603/concourse_test.git

jobs:
- name: executing-script
  plan:
  - get: git-repo
  - task: echo-message
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      inputs:
      - name: git-repo
      run:
        path: /bin/sh
        args:
        - -c
        - |
          echo "Printing A echo Message"
          pwd
          ls -lrta
          cat apache_logs
